---
title: "STA 9750 Mini-Project #01: What We Watched: Exploring Netflix Viewing Data"
author: "Nastassjia Durand"
date: "2026-09-27"
format:
  html:
    code-fold: true
    toc: true
---

***What is the Netflix What We Watched Report?***

- Netflix What We Watched Report - published every 6 months starting in 2023
- The "WWW" reports aggregate total global viewership for almost the entire Netflix catalog over six months periods
- The data is acquired to analyze viewership to make strategic decisions on the 2027 budget

### Step 1/ Data Ingest and Cleaning

**Goal**: ingest and clean the data to make it efficiently usable for analysis.

**Steps**: read, load the data into R and transform it.

1. Ingest the data using the `load_netflix_data()` function
2. Examine the data using the `View(NETFLIX_DATA)` feature
3. Fix column titles by adding a `rename()` step in the original acquisition code
4. Fix column types by adding a `mutate()` step in the original acquisition code 

*Note 1*: the following column titles were identified for the `rename()` cleaning process: `Title` - capital letter, `Runtime` - capital letter, `Views` - capital letter, `Hours Viewed`	- capitals and a space, `Release Date`	- capitals and a space and `Available Globally?` - capitals, a space, and a ?

*Note 2*: the following column titles were identified for the `mutate()` cleaning process: `year` - from `chr` to `int` and `available_globally` - from `chr` to `lgl`

Inspect the code by clicking on the drop-down menu below:
```{r}
#| label: load-data
#| message: false
#| warning: false
#' Acquire Netflix What We Watched Reports
#' 
#' This function will acquire and standardize all data for MP#01
#' from Netflix. Because Netflix hosts the data files behind a CDN, we
#' are accessing the release pages and automatically extracting links to the
#' relevant files (with CDN hash). 
#' 
#' After import, files are stacked vertically and some basic cleaning is
#' performed. 


load_netflix_data <- function(){
  # Note to students: Make sure you have installed the tidyverse and fs packages
  #                   before beginning this assignment. If you aren't sure,
  #                   simply run `library(tidyverse)` at your R Console and, if
  #                   you don't see an error message, `tidyverse` has been 
  #                   installed. (Same for `fs`) If you still need to install
  #                   either package, use the `install.packages` function as 
  #                   demonstrated in class.
  library(tidyverse)
  library(rvest)
  library(readxl)
  library(fs)
  
  data_dir <- path("data", "mp01")
    
  if(!dir_exists(data_dir)){
    dir_create(data_dir, showWarnings=FALSE, recurse=TRUE)
  }
  
  NETFLIX_URLS <- list(
    `2023H1` = "https://about.netflix.com/news/what-we-watched-a-netflix-engagement-report",
    `2023H2` = "https://about.netflix.com/news/what-we-watched-the-second-half-of-2023",
    `2024H1` = "https://about.netflix.com/news/what-we-watched-the-first-half-of-2024",
    `2024H2` = "https://about.netflix.com/news/what-we-watched-the-second-half-of-2024",
    `2025H1` = "https://about.netflix.com/news/what-we-watched-the-first-half-of-2025",
    `2025H2` = "https://about.netflix.com/news/what-we-watched-the-second-half-of-2025",
    `2026H1` = "https://about.netflix.com/news/what-we-watched-the-first-half-of-2026"
  )
  
  download_if_needed <- function(url, local){
    if(!file_exists(local)){
      download.file(url, local, quiet = TRUE, mode = "wb")
    }
    
    return(local)
  }
    
  NETFLIX_URLS |> 
    map(read_html) |> 
    map(html_element, xpath = "//a[contains(@href, '.xlsx')]") |> 
    map_chr(html_attr, "href") |> 
    enframe("period", "url") |> 
   mutate(path = path(data_dir, paste0(period, ".xlsx")), 
          path = map2(url, path, download_if_needed), 
          data = map(path, read_excel, skip=3, na="*"), 
          data = map(data, \(x) x |> mutate(`Release Date` = as.Date(`Release Date`)))) |>
    unnest(data) |> 
    select(-url, -path) |> 
    mutate(year=str_sub(period, 1, 4), 
           half=str_sub(period, start=6), 
           period_start = make_date(year, if_else(half==1, 1, 7), 1), 
           period_end = make_date(year, if_else(half==1, 7, 12), if_else(half==1, 30, 31))) |> 
    filter(!is.na(`Hours Viewed`)) |> 
    mutate(live_event = !is.na(Runtime) & str_detect(Runtime, "\\d+:\\d+\\*"), 
           clean_time = str_remove(Runtime, fixed("*")),
           Runtime = 60 * hour(hm(clean_time)) + minute(hm(clean_time))) |>
    select(-clean_time) |>
    mutate(Runtime = coalesce(Runtime, mean(Runtime, na.rm=TRUE)), 
           .by=Title, 
           Title = stringi::stri_trans_general(Title, "Latin-ASCII"),
           Title = str_remove(Title, " // .*"), 
           Title = str_remove(Title, "[^[:ascii:]].*"), 
           Title = str_trim(Title)) |>
    filter_out(Title == "") |>
    select(year, 
           period, 
           period_start, 
           period_end, 
           Title, 
           -half, 
           Runtime, 
           Views, 
           `Hours Viewed`, 
           `Release Date`,
           `Available Globally?`, 
           live_event) |>
    rename(title = Title,
           runtime = Runtime,
           views = Views,
           hours_viewed = `Hours Viewed`,
           release_date = `Release Date`,
           available_globally = `Available Globally?`) |>
    mutate(year = as.integer(year),
           available_globally = available_globally == "Yes")
}

NETFLIX_DATA <- load_netflix_data()
```

